stages:
  - test

unit-tests:
  stage: test
  image: python:3.10
  before_script:
    - apt-get update && apt-get install -y gcc
    - pip install -r requirements.txt -r requirements-test.txt
  script:
    - PYTHONPATH=$PYTHONPATH:. pytest tests/ -v --cov=app
